<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Protobuf Include="Protos\library.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Protos\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Google.Protobuf" />
  </ItemGroup>

</Project>
